FROM python:3.11.11 AS flask

WORKDIR /App

RUN python3 -m venv /App/venv

COPY requirements.txt /App/requirements.txt
RUN /App/venv/bin/pip install --no-cache-dir -r /App/requirements.txt

COPY . /App

EXPOSE 5000

CMD ["/App/venv/bin/python", "/App/app.py"]
